- name: Add SAPADM group and USER
  hosts: all
#  connection: local
  become: yes

  tasks:

  - name: Ensure group "sapadm" exists with group id 1001
    group:
      name: sapadm
      state: present
      gid: 1001

  - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
    user:
      name: johnd2
      comment: John Doe2
      uid: 1041
      group: sapadm
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
      password: "{{ 'Lab_123QWE' | password_hash('sha512') }}"
      update_password: on_create
    register: output

#  - name: Force change password
#    shell: chage -d 0 
#    when: output.changed
