- name: Add disk to SAP VM
  hosts: sap
#  connection: local
  become: yes

  tasks:

  - name: partition new disk pvcreate
    shell: 'pvcreate /dev/sde'
    args:
      executable: /bin/bash
    register: out_pvc

  - name: partition new disk vgcreate
    shell: 'vgcreate dg3 /dev/sde'
    args:
       executable: /bin/bash
    register: out_vgc
  - local_action: copy content="{{ out_vgc.stdout }}" dest="output_vgc_command.txt"

  - name: partition new disk lvcreate
    shell: 'lvcreate -n vol01 dg3 -l 100%FREE'
    args:
      executable: /bin/bash
    register: out_lvs
  - local_action: copy content="{{ out_lvs.stdout }}" dest="output_lvs_command.txt"


  - name: Makes file system on block device
    filesystem:
      fstype: ext4
      dev: /dev/mapper/dg3-vol01

  - name: new dir to mount
    file: path=/sapusr state=directory

  - name: mount the dir
    mount:
      path: /sapusr
      src: /dev/mapper/dg3-vol01
      fstype: ext4
      state: mounted
